<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Middle Name_middleName</name>
   <tag></tag>
   <elementGuidId>cd7d8142-e974-4cf5-abb8-7735f5aa013f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#middleName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='middleName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>159299cd-3052-496f-9227-f3dd28edb7d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInputText</value>
      <webElementGuid>731bcbda-48fc-49ef-9781-02e74cda57e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>6099b1d4-02bd-431d-90c2-34a31cdc1146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b148e3b3-1339-4f3c-ad9f-98cde72ef697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>middleName</value>
      <webElementGuid>3106d50f-6bbf-439d-a0cf-29828d88f1fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>middleName</value>
      <webElementGuid>172bef79-232d-43b6-a603-88512fe55148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;middleName&quot;)</value>
      <webElementGuid>ef7ac201-e134-4c3b-9df6-2935b30d2cac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='middleName']</value>
      <webElementGuid>f17a03c3-4c3f-4dbe-b85c-5953d8347ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmAddEmp']/fieldset/ol/li/ol/li[2]/input</value>
      <webElementGuid>b1452860-709b-4d55-bb1e-66c25eaf183a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ol/li[2]/input</value>
      <webElementGuid>5c7c5f5c-76b0-4f31-9c0f-155a05ba537e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'middleName' and @id = 'middleName']</value>
      <webElementGuid>0eee42ec-e71c-4267-a0e6-23690c43b2c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
