<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Middle Name_personaltxtEmpMiddleName</name>
   <tag></tag>
   <elementGuidId>ec491684-c983-4de7-9727-f301f31c8652</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#personal_txtEmpMiddleName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='personal_txtEmpMiddleName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e73ab072-28f5-4511-bd92-2823d7f17e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Trọng</value>
      <webElementGuid>9ba1699f-9d6f-45bb-835c-641ef9f26e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1b02ee73-81aa-4635-9020-ee1d036fc84e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personal[txtEmpMiddleName]</value>
      <webElementGuid>796cbc3f-ccde-4279-b374-8430a1add948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block default editable</value>
      <webElementGuid>035a8c99-7d56-4c45-8449-9ff071173025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>13d6220f-0286-40c6-a935-fe128fe1b40c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Middle Name</value>
      <webElementGuid>83e1ad0d-2f03-4779-986e-8725e1c17ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personal_txtEmpMiddleName</value>
      <webElementGuid>689544bd-17f6-4b6f-8c91-0ee312af3f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_txtEmpMiddleName&quot;)</value>
      <webElementGuid>b1d7ece7-5893-4acf-b238-b0647f08a5b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='personal_txtEmpMiddleName']</value>
      <webElementGuid>1e1a9401-e2a0-4df8-928b-cb266d68b30b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmEmpPersonalDetails']/fieldset/ol/li/ol/li[2]/input</value>
      <webElementGuid>19f74c09-e4e2-48cc-9bd8-cec84a4077d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/input</value>
      <webElementGuid>79446fd1-067b-4e95-a6e4-787c90761b37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'personal[txtEmpMiddleName]' and @title = 'Middle Name' and @id = 'personal_txtEmpMiddleName']</value>
      <webElementGuid>58b84b7b-14d4-447d-8977-9255b3b2a69e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
