<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Male_personaloptGender</name>
   <tag></tag>
   <elementGuidId>e174a998-2c91-421d-a331-3f3096a1afab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#personal_optGender_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='personal_optGender_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df83af44-5caa-401a-91cc-fca548d2f2bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personal[optGender]</value>
      <webElementGuid>f4fe1add-2a96-46e4-9682-8ab7ee2d5bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>065270d4-37ad-4976-a806-b0bf8cf8bdc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>50855090-2862-4d54-ad81-c40014b9b17e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personal_optGender_2</value>
      <webElementGuid>5175eb4a-daa8-46ed-a364-05838be17092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable</value>
      <webElementGuid>265a84aa-b082-4774-9e96-f5b60ffe1b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_optGender_2&quot;)</value>
      <webElementGuid>8f43eb8f-e387-445f-86aa-04caade07c8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='personal_optGender_2']</value>
      <webElementGuid>dfde0910-b51f-4aca-9d06-c7be588f054f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmEmpPersonalDetails']/fieldset/ol[3]/li/ul/li[2]/input</value>
      <webElementGuid>b36807c5-bd10-4e40-b1b2-bad0da3a7b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/li[2]/input</value>
      <webElementGuid>3eeb8b9f-8ac1-4818-b240-d4073d7d76b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'personal[optGender]' and @type = 'radio' and @id = 'personal_optGender_2']</value>
      <webElementGuid>fb954b3a-64a9-49b3-87c2-fd7c9582a6d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
