<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__personaltxtEmpLastName</name>
   <tag></tag>
   <elementGuidId>d5a68d9f-2ca9-41ad-829b-eb9e082a59a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#personal_txtEmpLastName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='personal_txtEmpLastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3020240f-124a-4d65-b28c-4ec5bf36355c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Trần</value>
      <webElementGuid>0f7a0acd-a689-4347-8603-fafc26768aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0a85f66a-0bc4-4db4-9f62-6055cb8ae422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personal[txtEmpLastName]</value>
      <webElementGuid>1e04c171-5e4f-402e-87b4-baa7dcf6c176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block default editable</value>
      <webElementGuid>3dbe0e3f-0e16-4f6e-9813-89338dd79a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>3d016b81-9c5d-4145-ae18-8acfbdd2647e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>4f2f7e48-2c86-4fed-a5ae-fb08a0bb5196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personal_txtEmpLastName</value>
      <webElementGuid>d6238631-3cc0-456c-85f1-38b7b022dfea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_txtEmpLastName&quot;)</value>
      <webElementGuid>4467f501-7bd4-4f33-9d64-5461dbbd19e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='personal_txtEmpLastName']</value>
      <webElementGuid>80abc1dc-d600-4b59-a069-0222895d1873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmEmpPersonalDetails']/fieldset/ol/li/ol/li[3]/input</value>
      <webElementGuid>0112f684-ee19-4ae2-9a06-76804d39944f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/input</value>
      <webElementGuid>16af76bb-4be1-4d89-a2c2-04a8bb12db80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'personal[txtEmpLastName]' and @title = 'Last Name' and @id = 'personal_txtEmpLastName']</value>
      <webElementGuid>b2d0ef20-0cfd-4aa2-a5f6-0ef2cad71dc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
