<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date of Birth_personalDOB</name>
   <tag></tag>
   <elementGuidId>f6125c3b-62ee-4068-9bfb-8a294c0da026</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#personal_DOB</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='personal_DOB']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>95b41423-7810-42c2-90a5-7a335f4b7300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personal_DOB</value>
      <webElementGuid>7af0a55e-71f2-40ee-a0ed-71a19856c0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2002-08-20</value>
      <webElementGuid>2de016aa-93a9-4fa2-b7f5-1209fda6f4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>415f5d4e-8ac0-4a7d-9f76-c19521acc5ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personal[DOB]</value>
      <webElementGuid>06175df9-1375-4eab-8f30-a17838e8b81e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable calendar hasDatepicker</value>
      <webElementGuid>7cbcff00-0031-48e5-87d9-3a021447728c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_DOB&quot;)</value>
      <webElementGuid>538fdc6f-4c08-4114-a167-ec9aa5055183</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='personal_DOB']</value>
      <webElementGuid>95588da7-dd48-46fb-9f23-4695e302725e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmEmpPersonalDetails']/fieldset/ol[3]/li[4]/input</value>
      <webElementGuid>397f2cc2-2d37-40d8-9b0b-a8f38984aaeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol[3]/li[4]/input</value>
      <webElementGuid>46994636-8f06-452c-8715-0e16252144b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'personal_DOB' and @type = 'text' and @name = 'personal[DOB]']</value>
      <webElementGuid>a6a7acc9-6800-4d86-b117-b8f5c938dd94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
