<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Gender_personaloptGender</name>
   <tag></tag>
   <elementGuidId>18db939f-829b-4bdf-a558-9698e8b66547</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#personal_optGender_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='personal_optGender_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef01416b-f2bc-4b66-a0df-668a5e410f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personal[optGender]</value>
      <webElementGuid>fe36de1d-1c78-4c1f-aa46-92583b83240c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f8786a45-c6d4-4390-b3b6-a0abc3356beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>762caef7-b255-4e07-b98f-67fc4872ba80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personal_optGender_1</value>
      <webElementGuid>8f609375-3cca-4165-82b1-a45451266745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>66bfbe5f-ca93-486a-9ec1-af210f732d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable</value>
      <webElementGuid>37ed9a9b-20f1-42c3-8dc0-7bb2256f593e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_optGender_1&quot;)</value>
      <webElementGuid>e20c9d1c-146e-45ea-aad8-8541ddc822dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='personal_optGender_1']</value>
      <webElementGuid>c19ce7cd-e4c0-4938-883b-1e622cc189df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmEmpPersonalDetails']/fieldset/ol[3]/li/ul/li/input</value>
      <webElementGuid>60f298a2-bc45-47a7-a6c6-c63993d6e1ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/li/input</value>
      <webElementGuid>19b2371a-e56d-45b6-b94b-076dcdfccf64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'personal[optGender]' and @type = 'radio' and @id = 'personal_optGender_1' and @checked = 'checked']</value>
      <webElementGuid>8c5919c6-ac5d-4b19-9681-cb10a22246ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
