<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_License Expiry Date_personaltxtLicExpDate</name>
   <tag></tag>
   <elementGuidId>44769dcf-43cb-4fa1-9551-63028139a9cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#personal_txtLicExpDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='personal_txtLicExpDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4bf739a5-43ef-4eb9-829b-1da0327f7a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personal_txtLicExpDate</value>
      <webElementGuid>c02f5a2e-fc34-446a-8e9d-285359ea9605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2023-01-01</value>
      <webElementGuid>8613aa26-d336-415f-9166-8ef4fd4f76c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e60fdfc1-e6ac-4c2d-8ff8-dc8592166177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personal[txtLicExpDate]</value>
      <webElementGuid>90e4770c-3ee8-42f9-8d2a-a151366d07a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calendar editable calendar hasDatepicker</value>
      <webElementGuid>09fc31f7-b55b-4116-91cd-87220ade9cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_txtLicExpDate&quot;)</value>
      <webElementGuid>46e1cb96-8d48-4fd6-a739-200e1f225241</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='personal_txtLicExpDate']</value>
      <webElementGuid>4e57895c-e54e-40c4-a87c-7d809cc2b5ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmEmpPersonalDetails']/fieldset/ol[2]/li[4]/input</value>
      <webElementGuid>936fcb94-8544-4172-93fb-443277cec83b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/input</value>
      <webElementGuid>f0197d06-5479-42e5-934c-6969d3f28378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'personal_txtLicExpDate' and @type = 'text' and @name = 'personal[txtLicExpDate]']</value>
      <webElementGuid>5509cd69-ab0e-4754-a8de-ca57a0facf05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
