<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_A Van</name>
   <tag></tag>
   <elementGuidId>61dc954f-7fa1-49a2-a7ab-b2cd052742b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='resultTable']/tbody/tr[10]/td[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>02d53cd2-9900-41e0-8b15-5b338ed1bc96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/orangehrm-4.5/symfony/web/index.php/pim/viewEmployee/empNumber/32001</value>
      <webElementGuid>67c198cb-1e18-4856-a7cc-7aec4a096bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>A Van</value>
      <webElementGuid>2bb5c752-be64-4783-b31e-b6dc31eb2f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resultTable&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[@class=&quot;left&quot;]/a[1]</value>
      <webElementGuid>775d1482-9b5c-4034-b4a4-308285cf305f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='resultTable']/tbody/tr[10]/td[3]/a</value>
      <webElementGuid>03de59f3-48c1-47b1-9027-a8a5d5493cde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'A Van')]</value>
      <webElementGuid>2c70d965-d3e6-4045-84f2-e5e690c12e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group6'])[2]/following::a[2]</value>
      <webElementGuid>b6cdf2a7-b715-49f5-aad2-798a9e9e7195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job'])[10]/following::a[2]</value>
      <webElementGuid>2238b835-9869-4d04-9ca3-fd4c157aea60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nguyen'])[1]/preceding::a[1]</value>
      <webElementGuid>78743eb6-806c-4898-97be-acb35277f0aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A Van'])[2]/preceding::a[3]</value>
      <webElementGuid>add133cb-fbcf-4cbf-ab15-b4a6e4e01129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='A Van']/parent::*</value>
      <webElementGuid>2663418d-6ed9-4f58-b05a-a36416c0d98a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/orangehrm-4.5/symfony/web/index.php/pim/viewEmployee/empNumber/32001')])[2]</value>
      <webElementGuid>cb61ee0c-f54e-4573-98ec-b8d7825d858c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[3]/a</value>
      <webElementGuid>631d499d-c204-45bc-ba0d-19fe45876e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/orangehrm-4.5/symfony/web/index.php/pim/viewEmployee/empNumber/32001' and (text() = 'A Van' or . = 'A Van')]</value>
      <webElementGuid>63b193f5-bf26-472c-bf7e-3be5b8a4697f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
