<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Employee Name_empsearchemployee_nameempName</name>
   <tag></tag>
   <elementGuidId>15aa9b99-7e7c-4f02-8a93-9bdd825b85ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='empsearch_employee_name_empName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#empsearch_employee_name_empName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ef1b83c-3089-493c-a990-c69f4dc32498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>802ce0a4-a719-4754-a81a-df6be50c76f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>empsearch[employee_name][empName]</value>
      <webElementGuid>e30f466f-15a0-44f9-9a31-4f397673cc14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>empsearch_employee_name_empName</value>
      <webElementGuid>2425c27c-5e20-4c1a-a70d-f60c1fc5ccc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ac_input</value>
      <webElementGuid>a9fa17ab-1752-439d-b517-a58e4057ab41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ce07aa47-4cd1-4f97-b207-4a9983bcac81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;empsearch_employee_name_empName&quot;)</value>
      <webElementGuid>b2c5d3bc-3da3-4550-b9f4-c8b1fab0e3a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='empsearch_employee_name_empName']</value>
      <webElementGuid>0acf67c6-a416-4262-b944-807842fd91c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_form']/fieldset/ol/li/input</value>
      <webElementGuid>a0f25b74-efbf-4c48-afc8-d65dd47eacb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>74e7070f-48be-430a-8d94-40f51e332cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'empsearch[employee_name][empName]' and @id = 'empsearch_employee_name_empName']</value>
      <webElementGuid>2a126aee-d4d0-4fc0-a6d5-8e2959053aac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
