<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LOGIN Panel_txtUsername</name>
   <tag></tag>
   <elementGuidId>2b1a741e-de61-4cf8-a579-7ad844f4eb4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtUsername']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtUsername</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4251dfdc-7675-449f-8ee0-dcf93df48d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtUsername</value>
      <webElementGuid>9be84081-16dd-4b60-814e-f0a069724bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtUsername</value>
      <webElementGuid>034d36c0-a2a4-47a2-8342-102f015f3120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>68766695-6f09-44cd-b100-4e5225122ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtUsername&quot;)</value>
      <webElementGuid>4f228f76-3552-4971-90c0-f7e60e51729e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtUsername']</value>
      <webElementGuid>1c6584db-e525-473e-bd1f-be8e275aa7e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divUsername']/input</value>
      <webElementGuid>aa42ce5b-1b6e-40ce-b1ee-dae23f849e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>5f7a8e3b-bcbc-4fa2-a28a-dd86b5b555e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtUsername' and @id = 'txtUsername' and @type = 'text']</value>
      <webElementGuid>db3c79c1-26f3-4201-851b-59614f12f33c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
