<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Employee Name_empsearchemployee_nameempName</name>
   <tag></tag>
   <elementGuidId>847f4c3f-2f3e-4a8a-8a58-0da7c5818e63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='empsearch_employee_name_empName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#empsearch_employee_name_empName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f36a6706-d96e-46ca-af94-a821c5daaa61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f74ea0c8-330a-4643-8021-8e36303a83a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>empsearch[employee_name][empName]</value>
      <webElementGuid>b28c91f6-3220-4336-b0f2-f06c7910990e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>empsearch_employee_name_empName</value>
      <webElementGuid>b41e5722-48ba-4c63-ae43-5c327457ac80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ac_input</value>
      <webElementGuid>31a3d2ce-a698-4ffe-b039-9e089abdcf0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7d3c3ff9-c102-4ee3-9b0a-021db302db9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;empsearch_employee_name_empName&quot;)</value>
      <webElementGuid>873dfb46-7e48-4f4c-982f-2beb0b96de92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='empsearch_employee_name_empName']</value>
      <webElementGuid>70c1063a-ad91-455f-8a81-92d32b2fc009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_form']/fieldset/ol/li/input</value>
      <webElementGuid>3ad70709-a851-4600-8427-b4baddd4d98d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>3e2279d6-30a5-44c2-b85d-494331974f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'empsearch[employee_name][empName]' and @id = 'empsearch_employee_name_empName']</value>
      <webElementGuid>10d94f2c-b019-4367-8a29-36682ec0025f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
