<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sub Unit__search</name>
   <tag></tag>
   <elementGuidId>2625d855-4d92-452a-a04a-c53ee3a731f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf4cecad-88f0-4e13-bf48-5b00476254cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>070cff9e-6a3f-41c3-88f6-f2d76d7a1a75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchBtn</value>
      <webElementGuid>1ff3c0ed-93ba-4269-b35f-c4e77c835447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>683e9ba3-31b8-4758-ad6e-99bc6d9e8cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_search</value>
      <webElementGuid>3dc1cb9c-1ddd-46bc-8f5a-fb6c2337223b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover</value>
      <webElementGuid>e232d994-1939-4566-b47f-e648020f0a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchBtn&quot;)</value>
      <webElementGuid>91940d92-de57-4ada-97bb-a3c9d0677505</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchBtn']</value>
      <webElementGuid>144677dd-1b13-4bb8-8116-78b010243d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_form']/fieldset/p/input</value>
      <webElementGuid>c62d71c2-d8db-402f-a02c-fb6fa2a4f004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>db70e220-1631-42d7-b82f-6625ccdb8acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'searchBtn' and @name = '_search']</value>
      <webElementGuid>bafb3c43-8e5d-4217-8438-25fcb82ac763</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
