<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Employee Id_employeeId</name>
   <tag></tag>
   <elementGuidId>01b1861a-c0d6-4272-abf6-5ecb87cc3c7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#employeeId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='employeeId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c904e83-02ad-4a87-96ba-9244023304a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInputText</value>
      <webElementGuid>2be4cd0e-54db-4b51-8224-0412d305a732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>42f46a9b-64c5-4e3f-82f7-9e56795d896d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a93ffba3-7ce8-4cf4-839a-de0baf091b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>employeeId</value>
      <webElementGuid>16ef8617-1f99-43a9-9556-0e99cb047834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0136</value>
      <webElementGuid>f2edd925-463d-498e-b0c1-4fc30e9fefa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>employeeId</value>
      <webElementGuid>ed744a98-3b8a-4620-a176-953bf05f1ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employeeId&quot;)</value>
      <webElementGuid>d69634e8-d0a0-4b95-8005-ba87245b139e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='employeeId']</value>
      <webElementGuid>cdb3fb5e-2814-4f49-afd8-948ab6a8c8d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmAddEmp']/fieldset/ol/li[2]/input</value>
      <webElementGuid>a29fc23c-a65b-471b-908e-8ffe903441fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/ol/li[2]/input</value>
      <webElementGuid>1e10d6e7-da59-4a2b-9a70-beebec3538cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'employeeId' and @id = 'employeeId']</value>
      <webElementGuid>03e80f51-1825-4068-99ca-7df2aeca01b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
