<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date of Birth_personalDOB</name>
   <tag></tag>
   <elementGuidId>3db9f0a0-6a43-4759-a3f1-dc9f0c4df73f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#personal_DOB</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='personal_DOB']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>439f148e-e749-4160-a3f6-d49e06a043f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personal_DOB</value>
      <webElementGuid>115b6ef4-eacc-4575-83a4-fa42b91dded8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2002-08-20</value>
      <webElementGuid>c3fe0091-7237-4a63-a23d-dd9734b6e14b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>032ea3bd-b642-4e4a-8f46-680828658568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personal[DOB]</value>
      <webElementGuid>73e2e45d-3ec8-41e8-9c2b-b9606c74956b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable calendar hasDatepicker</value>
      <webElementGuid>92c06c89-1c7c-43b7-9107-99c2d74e8c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_DOB&quot;)</value>
      <webElementGuid>8be67bf4-1284-4b70-ad09-9c95ee1b257e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='personal_DOB']</value>
      <webElementGuid>9a5ebb77-bd63-41ec-a9f7-82f513e01ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmEmpPersonalDetails']/fieldset/ol[3]/li[4]/input</value>
      <webElementGuid>9b21512e-985f-4b7a-a4bd-031b31cf6c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol[3]/li[4]/input</value>
      <webElementGuid>156be198-d5ed-49cb-9185-c4696a567399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'personal_DOB' and @type = 'text' and @name = 'personal[DOB]']</value>
      <webElementGuid>d1af4b72-dc77-4104-bc9f-8b70f368db77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
