<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__personaltxtEmpFirstName</name>
   <tag></tag>
   <elementGuidId>e494d3cf-3b34-46ca-9e92-ea02d2189b10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#personal_txtEmpFirstName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='personal_txtEmpFirstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e3e1d338-9cbb-4115-869b-e49d5cb906f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>77a3a9e2-9ed3-4fe0-a796-959061e99e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d02ddb32-f8d2-4b40-a772-99df6a6b44fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personal[txtEmpFirstName]</value>
      <webElementGuid>51ba3ffb-14ef-406a-ac70-08c09d8c80a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block default editable</value>
      <webElementGuid>f42616da-a595-4daa-8407-5029920c52bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>7da3a040-8e66-4dfb-a46e-559c789b20fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>First Name</value>
      <webElementGuid>ceb8d3c1-c531-4d2a-a613-12b5e07176d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personal_txtEmpFirstName</value>
      <webElementGuid>02cc6024-96dc-4f9e-bc93-b5c62da1f205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_txtEmpFirstName&quot;)</value>
      <webElementGuid>8e945dde-3e26-4144-adf6-49e8ccfda93b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='personal_txtEmpFirstName']</value>
      <webElementGuid>f743ea78-6af4-4161-8272-3f010f3dfe24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmEmpPersonalDetails']/fieldset/ol/li/ol/li/input</value>
      <webElementGuid>0ca1318c-3f4d-4d8c-98bf-ab1ec2652e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>f14871c9-c5a3-4a32-a5df-8edad3a9aa02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'personal[txtEmpFirstName]' and @title = 'First Name' and @id = 'personal_txtEmpFirstName']</value>
      <webElementGuid>b19b8ccb-19db-4c7a-9e9c-aae66071efed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
