<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Gender_personaloptGender</name>
   <tag></tag>
   <elementGuidId>3e687595-95f7-4f5d-a36b-ee612e3b181a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#personal_optGender_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='personal_optGender_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>515b1b44-0594-4f7a-ae62-58aefe858c98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personal[optGender]</value>
      <webElementGuid>fa96219f-93d1-4c37-915b-8506624a9911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8e2f4623-bd2a-4cea-b9ab-8312a6ac2b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e751f171-da1b-4a7c-add9-f74fb1574ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personal_optGender_1</value>
      <webElementGuid>402c7de0-4b1e-4e3e-ac0b-39a76eef800d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>1b4e9579-573e-4a1e-ae76-4cc6aec53796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable</value>
      <webElementGuid>58961f1a-3c45-4b52-9763-7ade964b1755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_optGender_1&quot;)</value>
      <webElementGuid>86dfe739-c86d-48ee-9944-881514082450</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='personal_optGender_1']</value>
      <webElementGuid>15116f34-cc17-4e48-ae15-573032b84e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmEmpPersonalDetails']/fieldset/ol[3]/li/ul/li/input</value>
      <webElementGuid>247e0f42-a887-480e-999b-224477a8d99f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/li/input</value>
      <webElementGuid>bdca9393-86b7-4c16-952a-fd1e10032e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'personal[optGender]' and @type = 'radio' and @id = 'personal_optGender_1' and @checked = 'checked']</value>
      <webElementGuid>dfaca352-b68a-42c3-ba37-433aa6ca0ec3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
