<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Required</name>
   <tag></tag>
   <elementGuidId>115a12d4-2e44-4ea4-a3ab-241aec04af72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmEmpPersonalDetails&quot;)/fieldset[1]/ol[1]/li[@class=&quot;line nameContainer&quot;]/ol[@class=&quot;fieldsInLine&quot;]/li[1]/span[@class=&quot;validation-error&quot;][count(. | //span[@for = 'personal_txtEmpFirstName' and @generated = 'true' and @class = 'validation-error' and (text() = 'Required' or . = 'Required')]) = count(//span[@for = 'personal_txtEmpFirstName' and @generated = 'true' and @class = 'validation-error' and (text() = 'Required' or . = 'Required')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.validation-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmEmpPersonalDetails']/fieldset/ol/li/ol/li/span</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>24c31d0f-1dd0-4d36-804d-7b213af56d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>personal_txtEmpFirstName</value>
      <webElementGuid>a8651ed9-db13-47fb-8250-ec64ee176a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>generated</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e760d610-f2e0-45a4-ad20-ccc362d13db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validation-error</value>
      <webElementGuid>3bd520fe-31bb-41f8-a36a-3078be3d768b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Required</value>
      <webElementGuid>ab2f1de5-706b-40e1-af88-4ad36a57ad19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmEmpPersonalDetails&quot;)/fieldset[1]/ol[1]/li[@class=&quot;line nameContainer&quot;]/ol[@class=&quot;fieldsInLine&quot;]/li[1]/span[@class=&quot;validation-error&quot;]</value>
      <webElementGuid>6d735486-2d74-4c21-9b5b-a2c07cc63af1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmEmpPersonalDetails']/fieldset/ol/li/ol/li/span</value>
      <webElementGuid>3b829247-5bdc-4568-932e-421111d34a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::span[1]</value>
      <webElementGuid>44e1d11b-f63e-41ee-ab86-1f2860035f18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Middle Name'])[1]/preceding::span[1]</value>
      <webElementGuid>352110d3-653a-4f99-942e-0b19ff0e1235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Required']/parent::*</value>
      <webElementGuid>515e97c7-ab48-415c-90f6-e4a65742ea2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/span</value>
      <webElementGuid>e6252cad-9d44-441a-802a-7c14a6583715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Required' or . = 'Required')]</value>
      <webElementGuid>4e1122ce-8a24-4a67-ae82-ff303d8490b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
