<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Employee Id_employeeId</name>
   <tag></tag>
   <elementGuidId>9951bc1b-b8f9-4f3c-a9b2-dd51c28f23a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#employeeId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='employeeId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34b82dd4-6dba-4aac-9d76-5cfc742b37bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInputText</value>
      <webElementGuid>4fc01ba7-fbab-4cb3-ba9d-140d1bcf9f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>1890587f-8b1f-499a-bd9e-77ab59594c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>433b3e18-c52f-4780-8bc4-80698acb4adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>employeeId</value>
      <webElementGuid>a67b6696-b9ac-4113-ae4d-63d289be82dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0146</value>
      <webElementGuid>d444f684-a8ed-48b0-a431-65d4f48f89ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>employeeId</value>
      <webElementGuid>0bab328b-5df1-471a-aa62-9fe5ae553ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employeeId&quot;)</value>
      <webElementGuid>2f1f20b2-45c0-4f41-847d-70a949a4ced2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='employeeId']</value>
      <webElementGuid>e4cd18f1-c17d-4bc9-8627-f2a690ffd05a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmAddEmp']/fieldset/ol/li[2]/input</value>
      <webElementGuid>bf0800f2-7f50-41f9-a467-07d64d9db706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/input</value>
      <webElementGuid>0617d0f5-5edb-41a6-aef7-12aaa4feb4fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'employeeId' and @id = 'employeeId']</value>
      <webElementGuid>f8682f9d-64c5-4bbd-be10-c405d349b9a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
